PREP(activateRscDetector);
PREP(deactivateRscDetector);
PREP(disableRscDetector);
PREP(enableRscDetector);
PREP(getSecondaryDetectedObject);
PREP(objectDetected);
PREP(screenInitRscDetector);
PREP(timeoutResetRscDetector);
PREP(toggleRscDetector);
