# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RIDTraceUtilityValueDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(555, 645)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.dialogLayout = QtWidgets.QHBoxLayout(Dialog)
        self.dialogLayout.setObjectName("dialogLayout")
        self.tracesBox = QtWidgets.QGroupBox(Dialog)
        self.tracesBox.setMaximumSize(QtCore.QSize(240, 16777215))
        self.tracesBox.setObjectName("tracesBox")
        self.tracesBoxLayout = QtWidgets.QVBoxLayout(self.tracesBox)
        self.tracesBoxLayout.setObjectName("tracesBoxLayout")
        self.tracesTable = TraceTableView(self.tracesBox)
        self.tracesTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tracesTable.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tracesTable.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tracesTable.setAlternatingRowColors(True)
        self.tracesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tracesTable.setObjectName("tracesTable")
        self.tracesBoxLayout.addWidget(self.tracesTable)
        self.dialogLayout.addWidget(self.tracesBox)
        self.tagsBox = QtWidgets.QGroupBox(Dialog)
        self.tagsBox.setObjectName("tagsBox")
        self.tagsBoxLayout = QtWidgets.QVBoxLayout(self.tagsBox)
        self.tagsBoxLayout.setObjectName("tagsBoxLayout")
        self.tagsList = QtWidgets.QListView(self.tagsBox)
        self.tagsList.setTabKeyNavigation(True)
        self.tagsList.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tagsList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tagsList.setObjectName("tagsList")
        self.tagsBoxLayout.addWidget(self.tagsList)
        self.tagButtonLayout = QtWidgets.QHBoxLayout()
        self.tagButtonLayout.setObjectName("tagButtonLayout")
        self.addTags = QtWidgets.QPushButton(self.tagsBox)
        self.addTags.setObjectName("addTags")
        self.tagButtonLayout.addWidget(self.addTags)
        self.reloadTags = QtWidgets.QPushButton(self.tagsBox)
        self.reloadTags.setObjectName("reloadTags")
        self.tagButtonLayout.addWidget(self.reloadTags)
        self.tagsBoxLayout.addLayout(self.tagButtonLayout)
        self.dialogLayout.addWidget(self.tagsBox)

        self.retranslateUi(Dialog)
        self.addTags.clicked.connect(Dialog.addTAG)
        self.reloadTags.clicked.connect(Dialog.reloadTAGS)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RID: Trace Value Editor"))
        self.tracesBox.setTitle(_translate("Dialog", "Traces"))
        self.tagsBox.setTitle(_translate("Dialog", "TAG\'s"))
        self.addTags.setText(_translate("Dialog", "Add a TAG"))
        self.reloadTags.setText(_translate("Dialog", "Reload TAG\'s"))
from RIDTraceUtilityValueDialogExtra import TraceTableView
